BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CustomerAuth (
    Auth_ID NUMBER PRIMARY KEY,
    Cust_ID NUMBER,
    Username VARCHAR2(100) UNIQUE,
    PasswordHash VARCHAR2(200),
    Created_At DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cauth_customer FOREIGN KEY (Cust_ID) REFERENCES Customer(Cust_ID)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;


